name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm ci
      - run: npm run build --if-present
      - run: rm-rf node_modules
      - uses: ./ # Uses an action in the root directory
      - uses: ./
        with:
          person: 'Adrian Etenyi'
